### PR TITLE
Warn about newlines in secrets (3.18)

### PR DESCRIPTION
**Pull request by thespad**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

------------------------------

 - [x] I have read the [contributing](https://github.com/linuxserver/docker-baseimage-alpine/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

## Description:
This is an attempt to deal with the dozens of people who create secrets with errant newlines. By default it will remove any newline characters from secrets before assigning to them envs. There is an undocumented bypass for the 3 people who will inevitably have some horrible edge case where they're legitimately using multi-line envs in secrets.

### CODE REVIEW

**Review by nemchik — DISMISSED** [review]
this looks fine, but the whole script might be better off rewritten at some point if we keep needing to nest more conditionals and loops like this.

**Comment by thespad** [comment]
Actually that's a good point, I hadn't noticed that since I made the changes to standardise this over all the bases during the s6v3 migration that there's a redundant if in there, fixed in 7c6601c

**Comment by thespad** [comment]
And then actually fixed in 1b98fd9

**Comment by nemchik** [comment]
> Actually that's a good point, I hadn't noticed that since I made the changes to standardise this over all the bases during the s6v3 migration that there's a redundant if in there, fixed in [7c6601c](https://github.com/linuxserver/docker-baseimage-alpine/commit/7c6601c83a5fa566cb2494b8ea8ff60bef3949fc)

I think most of it could be made into a function and then just the top line find command could exec the function. with that `find` we're also confirming the existence of the files that we're nesting in some `if` checks currently to reconfirm? (which seems a bit redundant)

**Comment by thespad** [comment]
No, we're confirming that the file that the FILE__ env points to exists, it's not a redundant check.

**Review by nemchik — APPROVED** [review]

**Pull request merged**
