### PR TITLE
Make 3.16 Fully v3 Compliant

### PR DESCRIPTION
**Pull request by thespad**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

------------------------------

 - [x] I have read the [contributing](https://github.com/linuxserver/docker-baseimage-alpine/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

## Description:
Fully v3ify the 3.16 base:

* Move custom services into `docker-mods` so they can be compiled into the v3 init
* Break `docker-mods` into functions to make it simpler to order
* [Handle dual-mode mods](https://github.com/linuxserver/docker-baseimage-alpine/commit/b5f9bf10939d1711942a857f77b4465e20935ac9)
* [Support universal mod package install](https://github.com/linuxserver/docker-baseimage-alpine/pull/103/commits/b7b477c8d6d2a8ccd8dcc6ccee5984282ef9743e)
* Notify users if they're using the old custom file/service paths
* [Bump s6 to 3.1.2.0, replace patch with STAGE2_HOOK, reduce logging level](https://github.com/linuxserver/docker-baseimage-alpine/pull/103/commits/ec2e9b7ac07789486e4aa32195190b9b475dfc8a)
* Integrate changes from https://github.com/linuxserver/docker-baseimage-alpine/pull/123
* [Use user2 bundle instead of top hack for ci-check](https://github.com/linuxserver/docker-baseimage-alpine/pull/103/commits/9c126e46cc8675d67cc3988ea144c3084cdd4ec3)
* [Bump s6 to 3.1.2.1 to fix regression](https://github.com/linuxserver/docker-baseimage-alpine/pull/103/commits/0e554393861e7915260341699b0a931debc61bb2)

Includes post-merge fixes from the other bases
* [Fix UMASK handling](https://github.com/linuxserver/docker-baseimage-alpine/pull/103/commits/74a451627101e81fce26ed3f6372e81add6609c9)
* [Set s6 service max timeout to 0](https://github.com/linuxserver/docker-baseimage-alpine/pull/103/commits/dd40de00b677662e1841c365e37ab2f57e1902d9)
* [Fix custom service logic](https://github.com/linuxserver/docker-baseimage-alpine/pull/103/commits/ef5ebc65e4bc2d774f95ae56ae8013ebc134f29f)
* [Rework legacy custom file handling](https://github.com/linuxserver/docker-baseimage-alpine/pull/103/commits/82d4508817c3719948c7b537419cd72b03a56d8e)

### CODE REVIEW

**Comment by nemchik** [comment]
Will we be looking at the new stage 2 hook to replace the patch method for mods in this pr?

**Comment by thespad** [comment]
> Will we be looking at the new stage 2 hook to replace the patch method for mods in this pr?

No because it doesn't exist in a published s6-overlay release yet, just in head.

**Review by nemchik — APPROVED** [review]
lgtm

**Comment by aptalca** [comment]
successful test with a locally built duckdns updated to s6v3

**Pull request merged**
