### PR TITLE
bump s6 to 1.22.0.0

### LINKED ISSUE #28: update s6 to latest version, doesn't sync disks on container shutdown.
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]
	

##  Thanks, team linuxserver.io

+ newest release of the overlay doesn't sync disks on shutdown of container. 
+ https://github.com/just-containers/s6-overlay#upgrade-notes
+ should help with some timeouts of container not shutting app down before/after sync (don't know order) but the s6 overlay readme mentions something along the lines of. 

+ pastebin here https://pastebin.com/G4squTjF shows no sync stage using the latest overlay vs the current one at the bottom
+ relevant lines for each containers exit are 33 for latest s6 and 85 for older version. no sync on the newer one. 
+ something @anoma was bitching about iirc...  
+ of course this applies to ubuntu baseimages too.

### PR DESCRIPTION
**Pull request by aptalca**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]
	

##  Thanks, team linuxserver.io

closes #28

### CODE REVIEW

**Comment by sparklyballs** [comment]
needs doing for ubuntu baseimages too.

**Comment by aptalca** [comment]
Right, but the branches are a bit confusing. Bionic branch is 5 commits ahead, 11 commits behind master?!? Trying to figure it out.

**Comment by sparklyballs** [comment]
just diff the dockerfiles...

**Comment by sparklyballs** [comment]
xenial baseimage is built from xenial branch 
likewise bionic is built from the bionic branch

no baseimage is built from master.

**Review by thelamer — APPROVED** [review]

**Pull request merged**
