### PR TITLE
Support adding user to more groups

### PR DESCRIPTION
**Pull request by zimme**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]
	

##  Thanks, team linuxserver.io

This change will add `-e PGIDS="1002 1003"` to allow the user to be added to more groups.

I needed this for my sickrage, couchpotato and transmission setup because I use different groups for
tvshows, movies and downloads etc.

The groups will be created with the names g1002, g1003 in the container where the name of the group
doesn't really matter.

### CODE REVIEW

**Comment by sparklyballs** [comment]
Thanks for your interest in our image, 

Not convinced this is required though to be honest, feel it would be better suited to have containers using the same group.

**Comment by zimme** [comment]
So how would I solve the case when I mount multiple volumes that have different user/group that I'm not in control over and the user running the process needs to be able to access all of those?

**Comment by anshulbajpai** [comment]
I am having a similar issue.
I use docker qbittorrent and after the torrent download is finished, I want to use "run external program" feature of qbittorrent to move downloaded file from one mounted volume (source) to another volume (destination) which is owned by a different user/group.

As of now, I have to pass the PGID as the group of destination mounted volume, so that writing is allowed at the destination. I am not happy with this approach.

If I could pass an additional group as @zimme mentioned, then I can keep the separation of users and groups clean. 

Let me know if there is any better way of achieving this.

**Comment by zimme** [comment]
My solution to this has been to move away from linuxserver's images in most cases in favor of my own or other images that don't handle user/groups in this way and instead use dockers own --user and --groupadd flags

**Pull request closed without merging**
